# Generated by Django 3.1.2 on 2020-10-24 15:51

from django.db import migrations, models

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_auto_20201024_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='district',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
