# Generated by Django 3.1.2 on 2020-10-24 18:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0004_auto_20201024_1852'),
    ]
 
    operations = [
        migrations.AddField(
            model_name='job',
            name='fee',
            field=models.CharField(default='', max_length=50, verbose_name='Ödenecek Ücret'),
        ),
        migrations.AlterField(
            model_name='job',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İşi Veren Kişi'),
        ),
        migrations.AlterField(
            model_name='job',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Bilgiler'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='job',
            name='district',
            field=models.CharField(default='', max_length=20, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=50, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Başlık'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='İsim')),
                ('comment_content', models.CharField(max_length=200, verbose_name='Yorum')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='job.job', verbose_name='İş')),
            ],
        ),
    ]
