# Generated by Django 3.1.2 on 2020-10-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20201024_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='E-Mail'),
        ),
        migrations.DeleteModel(
            name='Job1',
        ),
    ]
