# Generated by Django 3.1.2 on 2020-10-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20201025_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='telno',
            field=models.CharField(default='', max_length=20, verbose_name='Telefon Numarası'),
        ),
    ]
