# Generated by Django 3.1.2 on 2020-10-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_telno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_date']},
        ),
    ]
