# Generated by Django 3.1.2 on 2020-10-30 15:05

from django.db import migrations
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20201026_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=job.models.CICharField(default='', max_length=50, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
